version: "2"

services:
  certbot:
    build: certbot
    ports:
    - "80:80"
    volumes:
    - ${CERTBOT_CERTS_PATH}:/etc/letsencrypt
    environment:
    - CERTBOT_STANDALONE=true
    - CERTBOT_HOST
    - CERTBOT_EMAIL

volumes: 
  www: