version: "2"

services:
  certbot:
    image: ${REGISTRY_URL}/nginx-certbot
    volumes:
    - ${CERTBOT_CERTS_PATH}:/etc/letsencrypt
    - ${CERTBOT_WEBROOT}:/usr/share/nginx/html
    environment:
    - CERTBOT_STANDALONE=false
    - CERTBOT_HOST
    - CERTBOT_EMAIL

volumes: 
  www: